apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-webmvc
  name: eshop-webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-webmvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: eshop-webmvc
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: IdentityUrl
              value: http://:5105
            - name: IdentityUrlHC
              value: http://identity-api/hc
            - name: OrchestratorType
            - name: PurchaseUrl
              value: http://webshoppingapigw
            - name: SignalrHubUrl
              value: http://:5202
            - name: UseCustomizationData
              value: "True"
            - name: UseLoadTest
              value: "False"
          image: eshop/webmvc:linux-latest
          name: eshop-webmvc
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
