apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-sqldata
  name: eshop-sqldata
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 1433
  selector:
    io.kompose.service: eshop-sqldata
status:
  loadBalancer: {}
