apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-payment-api
  name: eshop-payment-api
spec:
  ports:
    - name: "5108"
      port: 5108
      targetPort: 80
  selector:
    io.kompose.service: eshop-payment-api
status:
  loadBalancer: {}
