apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-sqldata
  name: eshop-sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-sqldata
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: eshop-sqldata
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: Pass@word
          image: mcr.microsoft.com/azure-sql-edge:latest
          name: eshop-sqldata
          ports:
            - containerPort: 1433
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: eshop-sqldata
      restartPolicy: Always
      volumes:
        - name: eshop-sqldata
          persistentVolumeClaim:
            claimName: eshop-sqldata
status: {}
