apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-webmvc
  name: eshop-webmvc
spec:
  ports:
    - name: "5100"
      port: 5100
      targetPort: 80
  selector:
    io.kompose.service: eshop-webmvc
status:
  loadBalancer: {}
