apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eshop-rabbitmq
  name: eshop-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: eshop-rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management-alpine
          name: eshop-rabbitmq
          ports:
            - containerPort: 15672
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
